// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwtrbjznjckjfogxjndb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3dHJianpuamNramZvZ3hqbmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNjk0NDksImV4cCI6MjA5MDc0NTQ0OX0.WFggCbagzkevQD29Q3Bv7RBkx94bkcRQ5OAgqlI7mTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});